### ISSUE TITLE
Pls support null safe

### ISSUE THREAD

**Issue by buimanhhungit** [Earlybyte/aad_oauth#105]

**Comment by jacojvv-dev** [comment]
See #103

**Comment by buimanhhungit** [comment]
![image](https://user-images.githubusercontent.com/51559988/113271652-f553e380-9304-11eb-953a-9146cd8d8e1c.png)
 Not support at here. Pls check again.

**Comment by stevenebutler** [comment]
If you want to try the pull request out, you can use the following in your `pubspec.yaml`

But before you do, be warned that
* this PR changes the interface to the library a bit (due to the use of the flutter_webview package that works differently to the webview used in the current package).
* there is no guarantee the maintainers will accep the PR (especially due to the above point).

I'm happy to work with the maintainers to make changes that will still support my objectives of null safety/flutter 2 and mobile/web support though. :)

```yaml
  aad_oauth:
    git:
      url: https://github.com/stevenebutler/aad_oauth.git
      ref: null-safety
```

**Comment by buimanhhungit** [comment]
Tks.

**Comment by deanbot** [comment]
Not stale :) conversation happening in https://github.com/Earlybyte/aad_oauth/pull/103 though.

**Comment by stevenebutler** [comment]
Following discussion with the maintainers, I have created a new PR that only ports the library to null-safety and makes no API changes to the original `aad_oauth`.

You can test by using package source below, until it is accepted into the mainline `aad_oauth` package.

```yaml
  aad_oauth:
    git:
      url: https://github.com/stevenebutler/aad_oauth.git
      ref: null-safety-only
```
