### ISSUE TITLE
Use on web

### ISSUE THREAD

**Issue by JardarM** [Earlybyte/aad_oauth#106]
Hi,

can this package be used with flutter for web? If not, is it planned and are there other packages that support it?

**Comment by stevenebutler** [comment]
I have created an experimental pull request  #103, that adds flutter web support and null safety, but changes this package interface. If you want to try it out and provide feedback you can use the following in your `pubspec.yaml`

But before you do, be warned that
* this PR changes the interface to the library a bit (due to the use of the flutter_webview package that works differently to the webview used in the current package).
* there is no guarantee the maintainers will accept the PR (especially due to the above point).

```yaml
  aad_oauth:
    git:
      url: https://github.com/stevenebutler/aad_oauth.git
      ref: null-safety
```
